{
    "jobs": {
        "build": {
            "runs-on": "ubuntu-22.04",
            "permissions": {
                "contents": "write"
            },
            "steps": [
                {
                    "name": "Setup Java",
                    "run": "echo \"JAVA_HOME=$JAVA_HOME_17_X64\" >> \"$GITHUB_ENV\""
                },
                {
                    "with": {
                        "fetch-depth": "0"
                    },
                    "name": "Checkout",
                    "uses": "actions/checkout@v4"
                },
                {
                    "with": {
                        "path": "**/.gradle/loom-cache",
                        "key": "${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.*', '**/*.gradle*', '**/gradle-wrapper.properties') }}",
                        "restore-keys": "${{ runner.os }}-gradle-"
                    },
                    "name": "Cache",
                    "uses": "actions/cache@v3"
                },
                {
                    "with": {
                        "gradle-home-cache-cleanup": true
                    },
                    "name": "Setup Gradle",
                    "uses": "gradle/gradle-build-action@v2"
                },
                {
                    "uses": "fregante/setup-git-user@v2"
                },
                {
                    "name": "tagRelease",
                    "run": "./gradlew ",
                    "id": "tagrelease",
                    "env": {
                        "RELEASE_MAVEN_PASSWORD": "${{ secrets.RELEASE_MAVEN_PASSWORD }}",
                        "RELEASE_MAVEN_USER": "github",
                        "RELEASE_MAVEN_URL": "https://maven.lukebemish.dev/releases/",
                        "CURSEFORGE_KEY": "${{ secrets.CURSEFORGE_KEY }}",
                        "MODRINTH_KEY": "${{ secrets.MODRINTH_KEY }}"
                    }
                },
                {
                    "name": "Build",
                    "run": "./gradlew build",
                    "id": "build",
                    "env": {
                        "RELEASE_MAVEN_PASSWORD": "${{ secrets.RELEASE_MAVEN_PASSWORD }}",
                        "RELEASE_MAVEN_USER": "github",
                        "RELEASE_MAVEN_URL": "https://maven.lukebemish.dev/releases/",
                        "CURSEFORGE_KEY": "${{ secrets.CURSEFORGE_KEY }}",
                        "MODRINTH_KEY": "${{ secrets.MODRINTH_KEY }}"
                    }
                },
                {
                    "name": "Publish",
                    "run": "./gradlew publish modrinth curseforge",
                    "id": "publish",
                    "env": {
                        "RELEASE_MAVEN_PASSWORD": "${{ secrets.RELEASE_MAVEN_PASSWORD }}",
                        "RELEASE_MAVEN_USER": "github",
                        "RELEASE_MAVEN_URL": "https://maven.lukebemish.dev/releases/",
                        "CURSEFORGE_KEY": "${{ secrets.CURSEFORGE_KEY }}",
                        "MODRINTH_KEY": "${{ secrets.MODRINTH_KEY }}"
                    }
                },
                {
                    "run": "git push && git push --tags"
                }
            ]
        }
    },
    "name": "Release",
    "concurrency": "ci-${{ github.ref }}",
    "on": {
        "workflow_dispatch": {
            
        }
    }
}